### ISSUE TITLE
Same Jacobian? 

### ISSUE THREAD

**Issue by tsarikahin** [cmgcds/fastvpinns#13]
## Question
Thx a lot for the repo first of all. 

My question would be about the Helmholtz problem (https://github.com/cmgcds/fastvpinns/blob/main/examples/forward_problems_2d/complex_mesh/helmholtz2d/main_helmholtz.py)

Helmholtz problem has two components of the residual loss; x and y contributions, requiring two components of Jacobian (J_x and J_y) as  Kharizmi's implementation as well. However, you don't introduce the components of Jacobian. Or do I miss a point?

**Comment by thivinanandh** [comment]
The two components of jacobians calculated in 1D is multiplied  to get a single jacobian value at a given quadrature point in a 2D space.  This jacobian value is used to convert the test functions from reference domain to the actual domain. however, in fastVPINNs implementation, these calculations are performed internally within the FE module and the test function and its gradients are transfered to the actual domain, before being used in calculation of loss. 

please go through the implementation section of the fastVPINNs paper for more clarity.
